### ISSUE TITLE
AIO-futures example

### ISSUE THREAD

**Issue by ArtemGr** [lambdastackio/ceph-rust#2]
Just a heads up that I'm working on a futures-based high-level wrapper at https://github.com/ArtemGr/rados.hi.rs (I needed it real quick, so it was easier to roll my own crate rather than going through the contribution hoops with ceph-rust, sorry). Point is, it might serve as an example of how the AIO RADOS operations can be integrated with the trendy "futures" library.

**Comment by hanscj1** [comment]
We'll take a look. We have a new server agent project that builds on the tokio project for async i/o and futures. Thanks!!

**Comment by ArtemGr** [comment]
> We have a new server agent project that builds on the tokio project for async i/o and futures.

Sounds interesting. Drop me a link if/when there's something to look at.

**Comment by ArtemGr** [comment]
BTW, I'm starting the AIO operations proactively, when the future is created, but it's not necessarily the only way to implement the futures. I noticed that futures might be implemented in a "lazy evaluation" (aka "streaming") manner, where they only begin the computation when first `poll`ed for it. Not sure if lazy evaluation is a good call in this case though: in CPU-bound computations it serves to save the CPU cycles and make the infinite structures possible, but in the case of Ceph it is more important, at least to me, to overcome the latency by doing things in parallel. Another angle is that lazy evaluation's good when a lot of futures are _cancelled_, but it doesn't make sense when you're going to consume all the results.

**Comment by hanscj1** [comment]
Interesting things to note for Ceph. If you are running code on an OSD node then cpu is more important. On multi-core nodes that are running MONs or RGWs do not take up as much cpu. Network latency and traffic is really the most important thing in Ceph.

**Comment by ArtemGr** [comment]
A short follow up on my previous message.

I had an opportunity to work some more with the futures and it indeed seems that the default behaviour of the futures is supposed to be "lazy evaluation". ["futures do nothing unless polled"](https://github.com/alexcrichton/futures-rs/blob/1373749cb2ff4ce8c2f2d30b665ca1efdbcd8511/src/future/and_then.rs#L8).

So the Rust futures aren't parallel by default (which was a bit of a surprise because I'm used to the parallel futures in Scala).

To make them parallel, one has to jump through extra hoops, explicitly putting them in a `CpuPool` or in a parallel aggregator such as [join_all](https://github.com/alexcrichton/futures-rs/issues/254).

> If you are running code on an OSD node then cpu is more important.

I'm not so sure about that: Even SSD I/O might probably benefit from parallelism and if OSD uses spindle disks than I/O parallelism is still of utmost importance. Indeed, a local network latency is often considered less of an overhead than the spindle disk I/O latancy. Parallelism helps there by letting the operating system reorder disk operations to mimize the seek/throughput ratio.

**Comment by hanscj1** [comment]
Thanks for the update. CPU is critical on OSD nodes depending on the hardware config and how how Ceph is configured. That was the main point. Thanks again.

**Comment by ArtemGr** [comment]
In the reddit discussion - https://www.reddit.com/r/rust/comments/5lf7p3/are_futures_lazy/ - the subject of proactive vs. lazy futures were cleared. Turns out, a library is free to implement the futures any way it needs to. Proactive  or lazy evaluated - it's an implementation detail and not a part of the `futures` interface.
